server:
  port: 5000
spring:
  application:
    name: employee-app
  datasource:
    url: jdbc:mysql://database-2.cjeklvidjt6n.us-east-1.rds.amazonaws.com:3306/hr
    username: admin
    password: alka1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true